on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: podman build --pull=always --tag "localhost/${{ github.repository }}" .
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
    - run: podman push "localhost/${{ github.repository }}" "ghcr.io/${{ github.repository }}:latest"
